[package]
name = "reverse-proxy"
version = "0.0.1"
edition = "2021"

[dependencies]
tokio = { version = "=1.47.1", features = ["full"] }
hyper = { version = "=1.7.0", features = ["server", "client", "http1", "http2", "tcp"] }
url = "=2.5.7"  # For parsing URLs
