[package]
name = "reverse-proxy"
version = "0.0.1"
edition = "2021"

[dependencies]
tokio = { version = "=1.45.1", features = ["full"] }
hyper = { version = "=1.6.0", features = ["server", "client", "http1", "http2", "tcp"] }
url = "=2.5.4"  # For parsing URLs
