[package]
name = "reverse-proxy-hyper"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
tokio = { version = "=1.48.0", features = ["full"] }
hyper = { version = "=1.7.0", features = ["server", "client", "http1", "http2"] }
url = "=2.5.7"  # For parsing URLs
